# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Amir\Desktop\SteamPulse\steampulse\view\ui\converter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ConverterUi(object):
    def setupUi(self, Converter):
        Converter.setObjectName("Converter")
        Converter.resize(981, 571)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Converter)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.converter_crd = SimpleCardWidget(Converter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converter_crd.sizePolicy().hasHeightForWidth())
        self.converter_crd.setSizePolicy(sizePolicy)
        self.converter_crd.setBorderRadius(22)
        self.converter_crd.setObjectName("converter_crd")
        self.converter_lyt = QtWidgets.QHBoxLayout(self.converter_crd)
        self.converter_lyt.setSpacing(20)
        self.converter_lyt.setObjectName("converter_lyt")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.key_icon = IconWidget(self.converter_crd)
        self.key_icon.setObjectName("key_icon")
        self.horizontalLayout_2.addWidget(self.key_icon)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.key_spnbx = SpinBox(self.converter_crd)
        self.key_spnbx.setMinimumSize(QtCore.QSize(150, 33))
        self.key_spnbx.setMaximumSize(QtCore.QSize(150, 33))
        self.key_spnbx.setMinimum(1)
        self.key_spnbx.setMaximum(800)
        self.key_spnbx.setObjectName("key_spnbx")
        self.horizontalLayout_2.addWidget(self.key_spnbx)
        self.converter_lyt.addLayout(self.horizontalLayout_2)
        self.convert_icon = IconWidget(self.converter_crd)
        self.convert_icon.setObjectName("convert_icon")
        self.converter_lyt.addWidget(self.convert_icon)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.target_cmb = ComboBox(self.converter_crd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_cmb.sizePolicy().hasHeightForWidth())
        self.target_cmb.setSizePolicy(sizePolicy)
        self.target_cmb.setMinimumSize(QtCore.QSize(100, 0))
        self.target_cmb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.target_cmb.setObjectName("target_cmb")
        self.horizontalLayout_3.addWidget(self.target_cmb)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.target_lbl = SubtitleLabel(self.converter_crd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_lbl.sizePolicy().hasHeightForWidth())
        self.target_lbl.setSizePolicy(sizePolicy)
        self.target_lbl.setObjectName("target_lbl")
        self.horizontalLayout_3.addWidget(self.target_lbl)
        self.irt_icon = IconWidget(self.converter_crd)
        self.irt_icon.setObjectName("irt_icon")
        self.horizontalLayout_3.addWidget(self.irt_icon)
        self.converter_lyt.addLayout(self.horizontalLayout_3)
        self.converter_lyt.setStretch(0, 1)
        self.converter_lyt.setStretch(1, 1)
        self.converter_lyt.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.converter_crd)

        self.retranslateUi(Converter)
        QtCore.QMetaObject.connectSlotsByName(Converter)

    def retranslateUi(self, Converter):
        _translate = QtCore.QCoreApplication.translate
        Converter.setWindowTitle(_translate("Converter", "Converter"))
from qfluentwidgets import ComboBox, IconWidget, SimpleCardWidget, SpinBox, SubtitleLabel
